Repository nathangreen1632/career-gist, pull requests merged in 2025-02, with the labels that each got.

#27 ngreen/serverBuild
  server/package-lock.json
  server/package.json
  server/src/server.ts
Labels: enhancement

#26 ngreen/redisCache
  server/src/cache/redisCacheService.ts
  server/src/routes/favorites.ts
  server/src/routes/jobs.ts
  server/src/services/api/gptAPI.ts
Labels: enhancement

#28 (feat: add) integrated `favorites` and `gptAPI` routes in `index.ts`
  server/src/routes/index.ts
Labels: enhancement

#31 (chore: cleanup) removed unused files, refactored and updated code...
  client/index.html
  package.json
  server/db/config/database.ts
  server/db/schema.sql
  server/db/seeds/index.ts
  server/src/cache/cacheCleanup.ts
  server/src/cache/redisCacheService.ts
  server/src/config/database.ts
  server/src/models/JobModel.ts
  server/src/models/index.ts
  server/src/routes/favorites.ts
  server/src/routes/index.ts
  server/src/routes/jobsRoutes.ts
  server/src/seeds/index.ts
  server/src/server.ts
  server/src/services/api/gitHubAPI.ts
Labels: cleanup

#32 created files for the HomePage Components
  client/src/App.tsx
  client/src/components/BgImage.tsx
  client/src/components/HomeButtons.tsx
  client/src/components/Logo.tsx
  client/src/components/MainHead.tsx
  client/src/components/Navbar.tsx
  client/src/components/SearchBar.tsx
  client/src/components/SubHead.tsx
Labels: documentation

#33 created pages
  client/src/pages/AppliedTo.tsx
  client/src/pages/Error.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/LogIn.tsx
  client/src/pages/SavedJobs.tsx
  client/src/pages/SignUp.tsx
Labels: documentation

#34 added Footer page and base codes in main.tsx
  client/src/main.tsx
  client/src/pages/Footer.tsx
Labels: documentation

#35 Cc maintsx
  client/src/main.tsx
  client/src/pages/Error.tsx
  client/vite.config.ts
  package-lock.json
  package.json
  server/tsconfig.json
Labels: bug, documentation

#37 added foundation code for MainHead
  client/src/components/MainHead.tsx
Labels: documentation, enhancement

#39 deleted BgImage component
  client/src/components/BgImage.tsx
Labels: documentation, cleanup

#45 READY FOR MERGE
  .gitignore
  client/src/App.css
  client/src/App.tsx
  client/src/Pages/AppliedToPage.tsx
  client/src/Pages/ErrorPage.tsx
  client/src/Pages/HomePage.tsx
  client/src/Pages/Login.tsx
  client/src/Pages/NotFoundPage.tsx
  client/src/Pages/SavedJobs.module.css
  client/src/Pages/SavedJobs.tsx
  client/src/components/JobItem.tsx
  client/src/components/JobList.module.css
  client/src/components/JobList.tsx
  client/src/components/Layout.tsx
  client/src/components/Navbar.tsx
  client/src/components/SearchForm.tsx
  client/src/components/Spinner.css
  client/src/components/Spinner.tsx
  client/src/contexts/JobsContext.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/types/types.ts
Labels: documentation, enhancement

#48 ngreen/backendOptimizations
  client/tsconfig.json
  client/vite.config.ts
  server/package-lock.json
  server/package.json
  server/src/cache/cacheCleanup.ts
  server/src/cache/redisCacheService.ts
  server/src/routes/api/gptRoutes.ts
  server/src/routes/favorites.ts
  server/src/routes/index.ts
  server/src/routes/jobsRoutes.ts
  server/src/server.ts
  server/src/services/auth-routes.ts
  server/src/services/index.ts
  server/src/services/jSearchServices.ts
  server/tsconfig.json
  shared/package.json
  shared/tsconfig.json
  shared/types/index.ts
  shared/types/jobSearch.ts
Labels: enhancement

#49 ngreen/rateLimiting
  client/tsconfig.json
  client/vite.config.ts
  server/package-lock.json
  server/package.json
  server/src/cache/cacheCleanup.ts
  server/src/cache/redisCacheService.ts
  server/src/middleware/rateLimiter.ts
  server/src/routes/api/gptRoutes.ts
  server/src/routes/favorites.ts
  server/src/routes/index.ts
  server/src/routes/jobsRoutes.ts
  server/src/server.ts
  server/src/services/auth-routes.ts
  server/src/services/index.ts
  server/src/services/jSearchServices.ts
  server/tsconfig.json
  shared/package.json
  shared/tsconfig.json
  shared/types/index.ts
  shared/types/jobSearch.ts
Labels: enhancement

#51 Cc/designs
  client/src/App.css
  client/src/App.tsx
  client/src/Pages/AppliedToPage.tsx
  client/src/Pages/HomePage.css
  client/src/Pages/HomePage.tsx
  client/src/Pages/Login.css
  client/src/Pages/Login.tsx
  client/src/Pages/SavedJobs.tsx
  client/src/components/JobItem.tsx
  client/src/components/JobList.tsx
  client/src/components/Layout.tsx
  client/src/components/Navbar.tsx
  client/src/components/SearchForm.tsx
  client/src/contexts/JobsContext.tsx
  client/src/main.tsx
  client/src/types/types.ts
  server/.env.EXAMPLE
Labels: enhancement

#52 ngreen/frontendConnect
  client/package.json
  client/src/Pages/HomePage.tsx
  client/src/components/JobList.tsx
  client/vite.config.ts
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/server.ts
Labels: enhancement

#53 Snabaj/database connection
  client/src/components/JobList.tsx
  server/package.json
  server/src/models/JobQueryModel.ts
  server/src/models/companyModel.ts
  server/src/models/index.ts
  server/src/models/jobContactInfoModel.ts
  server/src/models/jobsModel.ts
  server/src/models/skillsModel.ts
  server/src/seeds/company-seeds.ts
  server/src/seeds/index.ts
  server/src/seeds/job-seeds.ts
  server/src/seeds/jobContactInfo-seeds.ts
  server/src/seeds/skill-seeds.ts
  server/src/server.ts
  server/src/services/jSearchServices.ts
Labels: enhancement

#54 ngreen/depsRollback
  client/package-lock.json
  client/src/Pages/HomePage.tsx
  client/vite.config.ts
  package-lock.json
  package.json
  server/package-lock.json
  server/src/routes/api/index.ts
  server/src/routes/index.ts
  server/src/server.ts
Labels: enhancement, cleanup

#56 ngreen/sharedInterface
  client/package.json
  client/src/Pages/HomePage.tsx
  client/src/types/interface/jobSearch.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  package.json
  server/src/server.ts
  server/src/types/interface/jobSearch.ts
Labels: enhancement, cleanup

#58 (feat: enhancement) Refactor job data handling and caching with GPT enhancement
  server/src/cache/redisCacheService.ts
  server/src/routes/api/gptRoutes.ts
  server/src/routes/api/jSearchRoutes.ts
  server/src/services/gptService.ts
  server/src/services/jSearchServices.ts
Labels: enhancement

#59 Snabaj/logins
  client/src/Pages/Login.tsx
  client/src/api/authApi.tsx
  client/src/interfaces/UserData.tsx
  client/src/interfaces/UserLogin.tsx
  client/src/utils/auth.ts
  server/src/models/JobQueryModel.ts
  server/src/routes/auth-routes.ts
  server/src/routes/index.ts
  server/src/seeds/user-seeds.ts
Labels: enhancement

#60 (feat: update) Enhance authentication, caching, and build process
  package.json
  server/package.json
  server/src/cache/redisCacheService.ts
  server/src/models/index.ts
  server/src/routes/auth-routes.ts
  server/src/server.ts
Labels: bug, enhancement

#66 (chore: refactor) Refactor job data enhancement logic
  server/src/services/gptService.ts
Labels: enhancement, cleanup

#65 Cc/debug2
  client/index.html
  client/src/App.css
  client/src/Pages/AppliedToPage.tsx
  client/src/Pages/Footer.module.css
  client/src/Pages/Footer.tsx
  client/src/Pages/HomePage.css
  client/src/Pages/HomePage.tsx
  client/src/Pages/Login.css
  client/src/Pages/SavedJobs.tsx
  client/src/assets/github-mark.png
  client/src/components/JobDescription.tsx
  client/src/components/JobList.module.css
  client/src/components/JobList.tsx
  client/src/components/SearchForm.tsx
  client/src/contexts/JobsContext.tsx
  client/src/types/types.ts
  client/src/types/types/fetchDummyJobs.ts
Labels: enhancement

#70 ngreen/rawDataDisplay
  LICENSE
  README.md
  client/src/Pages/HomePage.tsx
  server/src/routes/api/jSearchRoutes.ts
  server/src/services/gptService.ts
Labels: bug, enhancement

#72 (chore: fix) Add logging for Redis connection and caching operations
  server/src/cache/redisCacheService.ts
Labels: bug, enhancement, cleanup

#73 (chore: fix) Refactor Redis logging and enhance caching feedback
  server/src/cache/redisCacheService.ts
Labels: bug, enhancement, cleanup
